[build]
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "build"
  # Location of built function code
  functions = "functions-build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control= "no-cache, no-store, must-revalidate"

# /* site=:site /.netlify/functions/do-login?site=:site 302! Role=*
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/do-login"
  status = 302
  force = true
  query = {site = ":site"}
  conditions = {Role = ["admin"]}
# /* 	/index.html	 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
